POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhbG11YWEiLCJpZCI6IjVkMWM1MzIwY2U2MDQwMGNmYzI2ZjJmMCIsImlhdCI6MTU2MjEzNzQ3NH0.Hjj3ftX8bj0QhndkonY9SucsDlaNCA7mXMd5bD6JaDA


{
  "title": "Aarotus added a blog", 
  "author": "Kimmo Runsala",
  "url": "runsalasites.home.fi"  
}